### ISSUE TITLE
Gerência da Produção do Livro de LIBRAS

### ISSUE THREAD

**Issue by edusantana** [ciencias-agrarias-ead/libras-livro#1]
- [ ] Primeira Reunião com os Autores (Agendada para 15/6 -> adiada para 19/6)
- [ ] Criação de uma extensão para para possibilitar incluir vídeos (asciidoctor/asciidoctor-extensions-lab#45)
- [x] [Criação de um repositório para salvar referências aos vídeos e imagens de LIBRAS](https://github.com/sign-languages/libras)
- [ ] Criação de uma ferramenta para popular repositório a partir de listas no youtube (sign-languages/create-sign-repository#1)
- [ ] Popular repositório utilizando a ferramenta de extração de dados do youtube. (sign-languages/libras#1)
